### PR TITLE
Create .gitignore

### PR DESCRIPTION
**Pull request by Illviljan**
Add `.gitignore` to remove weird diffs in `dcmReader.egg-info` when installing a developer version. 

This is how I installed it:
* Fork repository
* git cloned it.
* Made a conda environment.
* cd to the dcmreader directory, and `pip install -e .`

### CODE REVIEW

**Comment by Illviljan** [comment]
cc @dkuschmierz :)

**Comment by dkuschmierz** [comment]
Is this a file you created on your own or was it copied somewhere? If yes, are there any license requirements?

**Comment by Illviljan** [comment]
That particular one was from https://github.com/tomwhite/cubed/blob/main/.gitignore but I had checked a few other repos and it looked very similar to each other.

The new one is from https://github.com/github/gitignore/blob/main/Python.gitignore
They use CC0-1.0 license which should be fine, right?

**Review by dkuschmierz — APPROVED** [review]
Yes, this should be fine!

**Pull request merged**
